server:
  port: 8080
  servlet:
    context-path: /

### 文档配置
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  # 配置
  setting:
    enableFooter: false
    enableFooterCustom: true
#    footerCustomContent: Copyright  2021-[零售动向](https://insight.jd.com)
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: false
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
  documents:
    - group: 1.0版本
      name: 自定义文档
      # 某一个文件夹下所有的.md文件
      locations: classpath:statics/summarize.md